### ISSUE TITLE
Extend the game map JSON file to include more interconnected rooms

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-kaboom-rpg#14]
Extend the game map JSON file to include more interconnected rooms - check out the video in the README.md file and the README contents for details on how this works. Design a cool map :)

This issue builds on work done in a previous successful Hacktoberfest pull request [here](https://github.com/redis-developer/redis-kaboom-rpg/pull/11) - check it out for an example of how to do this well.

This is part of our participation in Hacktoberfest 2021. Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by simonprickett** [comment]
@sumitsawant hi there, just checking in to see how it's going.  All well?

**Comment by sumitsawant** [comment]
@simonprickett , I'm really sorry , I was not able to take a look as I was completely swamped at work . I can finish this by coming Saturday if you can wait otherwise you can assign this to someone else . Thanks !
