### ISSUE TITLE
Extend the game map JSON file to include more interconnected rooms

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-kaboom-rpg#3]
Extend the game map JSON file to include more interconnected rooms - check out the video in the `README.md` file and the README contents for details on how this works.  Design a cool map :)

This is part of our participation in Hacktoberfest 2021.  Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us?  Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by Sarahjdes** [comment]
I'd like to contribute to this one, can you assign it to me?

**Comment by Sarahjdes** [comment]
My PR has been opened, my Twitter and Discord usernames are both **Sarahjdes**

Let me know if anything is missing!

**Comment by SuzeShardlow** [comment]
Thanks @Sarahjdes!  We would love to chat to you some more about your contribution - would you be able to reach out to me and @simonprickett at redis.university@redis.com ?  Thanks!

This issue has been closed by #11.
